export const filterableData = [
  {
    name: 'Bolalar',
    src: '/assets/images/bolalar/msg5028133006-86316.jpg',
    title: 'Mountains',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    name: 'Bolalar',
    src: '/assets/images/bolalar/msg5028133006-86317.jpg',
    title: 'Mountains',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    name: 'Bolalar',
    src: '/assets/images/bolalar/msg5028133006-86318.jpg',
    title: 'Mountains',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    name: 'Bolalar',
    src: '/assets/images/bolalar/msg5028133006-86319.jpg',
    title: 'Mountains',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    name: 'Bolalar',
    src: '/assets/images/bolalar/msg5028133006-86320.jpg',
    title: 'Mountains',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    name: 'Bolalar',
    src: '/assets/images/bolalar/msg5028133006-86321.jpg',
    title: 'Mountains',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    name: 'Bolalar',
    src: '/assets/images/bolalar/msg5028133006-86322.jpg',
    title: 'Mountains',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    name: 'Bolalar',
    src: '/assets/images/bolalar/msg5028133006-86323.jpg',
    title: 'Mountains',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    name: 'Oshxona',
    src: '/assets/images/oshxona/msg5028133006-86329.jpg',
    title: 'Merceres moshinasi',
    text: 'Mercedesni bizdan sotib',
  },
  {
    name: 'Oshxona',
    src: '/assets/images/oshxona/msg5028133006-86330.jpg',
    title: 'Merceres moshinasi',
    text: 'Mercedesni bizdan sotib',
  },
  {
    name: 'Oshxona',
    src: '/assets/images/oshxona/msg5028133006-86331.jpg',
    title: 'Merceres moshinasi',
    text: 'Mercedesni bizdan sotib',
  },
  {
    name: 'Oshxona',
    src: '/assets/images/oshxona/msg5028133006-86332.jpg',
    title: 'Merceres moshinasi',
    text: 'Mercedesni bizdan sotib',
  },
  {
    name: 'Oshxona',
    src: '/assets/images/oshxona/msg5028133006-86333.jpg',
    title: 'Merceres moshinasi',
    text: 'Mercedesni bizdan sotib',
  },
  {
    name: 'Oshxona',
    src: '/assets/images/oshxona/msg5028133006-86334.jpg',
    title: 'Merceres moshinasi',
    text: 'Mercedesni bizdan sotib',
  },
  {
    name: 'Oshxona',
    src: '/assets/images/oshxona/msg5028133006-86335.jpg',
    title: 'Merceres moshinasi',
    text: 'Mercedesni bizdan sotib',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86338.jpg',
    title: 'Modeller',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86339.jpg',
    title: 'Modeller',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86340.jpg',
    title: 'Modeller',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86341.jpg',
    title: 'Modeller',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86342.jpg',
    title: 'Modeller',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86343.jpg',
    title: 'Modeller',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86344.jpg',
    title: 'Modeller',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86345.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86346.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86347.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86348.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86349.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86350.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86351.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86352.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86353.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86354.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86355.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86356.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86357.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86358.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86359.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Yotoqxona',
    src: '/assets/images/yotoqxona/msg5028133006-86360.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Mexmonxona',
    src: '/assets/images/mexmonxona/msg5028133006-86363.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Mexmonxona',
    src: '/assets/images/mexmonxona/msg5028133006-86364.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Mexmonxona',
    src: '/assets/images/mexmonxona/msg5028133006-86365.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Mexmonxona',
    src: '/assets/images/mexmonxona/msg5028133006-86366.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Mexmonxona',
    src: '/assets/images/mexmonxona/msg5028133006-86367.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Mexmonxona',
    src: '/assets/images/mexmonxona/msg5028133006-86368.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Mexmonxona',
    src: '/assets/images/mexmonxona/msg5028133006-86369.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Mexmonxona',
    src: '/assets/images/mexmonxona/msg5028133006-86370.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Mexmonxona',
    src: '/assets/images/mexmonxona/msg5028133006-86371.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Mexmonxona',
    src: '/assets/images/mexmonxona/msg5028133006-86372.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Mexmonxona',
    src: '/assets/images/mexmonxona/msg5028133006-86373.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Mexmonxona',
    src: '/assets/images/mexmonxona/msg5028133006-86374.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Mexmonxona',
    src: '/assets/images/mexmonxona/msg5028133006-86375.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Mexmonxona',
    src: '/assets/images/mexmonxona/msg5028133006-86376.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Mexmonxona',
    src: '/assets/images/mexmonxona/msg5028133006-86377.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Mexmonxona',
    src: '/assets/images/mexmonxona/msg5028133006-86378.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Mexmonxona',
    src: '/assets/images/mexmonxona/msg5028133006-86379.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Mexmonxona',
    src: '/assets/images/mexmonxona/msg5028133006-86380.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Mexmonxona',
    src: '/assets/images/mexmonxona/msg5028133006-86381.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Mexmonxona',
    src: '/assets/images/mexmonxona/msg5028133006-86382.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Mexmonxona',
    src: '/assets/images/mexmonxona/msg5028133006-86383.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Hammom',
    src: '/assets/images/hammom/msg5028133006-86305.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Hammom',
    src: '/assets/images/hammom/msg5028133006-86306.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Hammom',
    src: '/assets/images/hammom/msg5028133006-86307.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Hammom',
    src: '/assets/images/hammom/msg5028133006-86308.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Hammom',
    src: '/assets/images/hammom/msg5028133006-86309.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Hammom',
    src: '/assets/images/hammom/msg5028133006-86310.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Hammom',
    src: '/assets/images/hammom/msg5028133006-86311.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Hammom',
    src: '/assets/images/hammom/msg5028133006-86312.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Hammom',
    src: '/assets/images/hammom/msg5028133006-86313.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Hammom',
    src: '/assets/images/hammom/msg5028133006-86314.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Koridor',
    src: '/assets/images/karidor/msg5028133006-86387.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Koridor',
    src: '/assets/images/karidor/msg5028133006-86384.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
  {
    name: 'Koridor',
    src: '/assets/images/karidor/msg5028133006-86385.jpg',
    title: 'УЮТ потолок',
    text: 'Турткуль Натяжные потолки',
  },
];
